version: 1
disable_existing_loggers: false

formatters:
  default:
    (): dcs_pylot_dash.log_formatter.ISO8601MicrosecondsFormatter
    format: '%(asctime)s %(levelname)-8s [%(name)s]   %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

loggers:
  dcs_pylot_dash:
    level: INFO
    handlers: [ console ]
    propagate: false

  fastapi:
    level: INFO
    handlers: [ console ]
    propagate: false

  uvicorn:
    level: INFO
    handlers: [ console ]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [ console ]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [ console ]
    propagate: false

root:
  level: INFO
  handlers: [ console ]
