/**
 * Copyright (c) 2026 Kevin Rzepka <kdev@posteo.com>
 * SPDX-License-Identifier: MIT
 * License-Filename: LICENSE
 */
import { Component } from '@angular/core';
import { Card } from 'primeng/card';
import { AppConstants } from '../constants';

export type FAQEntry = {
  q: string;
  a: string;
};

@Component({
  selector: 'app-faq',
  imports: [Card],
  templateUrl: './faq.html',
  styleUrl: './faq.css',
})
export class Faq {
  protected header: string = `${AppConstants.APP_NAME} - FAQ`;

  entries: FAQEntry[] = [
    {
      q: 'What is this?',
      a: 'This is a free open-source tool to generate Lua and HTML code, that allows to show live plane telemetry data from the video game "DCS World".',
    },
    {
      q: 'Is this tool in any way officially connected to DCS World, Eagle Dynamics SA or any of its subsidiaries?',
      a: 'No. This is a non-commercial open source project.',
    },
    {
      q: "What's the point of this tool when I have a modern HUD, like in the F/A-18 or F-16?",
      a: "For modern jets, the benefit is limited of course. It's very useful for older jets with hard-to-read instrument panels though; looking at you, True Airspeed indicator of the F-4.",
    },
    {
      q: 'Can I use the generated code along with other tools, that are configured in my Export.lua, e.g., SRS?',
      a: 'Yes. The generated code does not interfere with other tools in any way (unless they were to bind to the same TCP port as the Lua HTTP server of this tool, which is highly unlikely). Should the TCP port indeed be in use, you can change it via the advanced settings.',
    },
    {
      q: 'How does the generated code work on my machine?',
      a: 'Simplified: DCS offers a Lua programming interface to export data. The code generated by this tool uses this Lua interface to retrieve the data and opens a TCP socket, which will send HTTP responses. The generated HTML page contains Javascript, which accesses the socket via HTTP, retrieves the data, and displays it.',
    },
    {
      q: 'How do I remove, i.e. uninstall the generated code from my DCS World installation?',
      a: 'Revert your C:\\Users\\<username>\\Saved Games\\DCS\\Scripts\\Export.lua file to its original state, or remove the lines which you added during the installation of the generated code.',
    },
    {
      q: 'Can I display the data on a different machine than the one running DCS?',
      a: 'Yes. You can modify the bind address in the advanced settings. Depending on your network configuration, you might have to adjust routing and firewall settings. This is recommended only for advanced users, who understand the security implications.',
    },
    {
      q: 'Does the generated code use any external resources?',
      a: 'Yes, it downloads the Bootstrap Javascript framework and a font from Google Fonts. If this is a problem for you, you are free to download these resources yourself and replace them in the generated HTML file.',
    },
    {
      q: 'Does using the dashboards generated with this tool affect the DCS integrity check (IC)?',
      a: 'No, but whether they work or not depend on the server settings. Most servers do allow exporting ownship data though, which is the only requirement for these dashboards to work.',
    },
    {
      q: 'Can I also show Radar, RWR and/or target data?',
      a: 'No, this would require the server to allow exporting of sensor and/or world data, which most servers do not allow (for a very good reason, since this would facilitate "hacking").',
    },
    {
      q: 'Can I use the Lua HTTP server directly, without using the generated HTML UI?',
      a: 'Yes. It runs on your machine, do what you want with it. For example, you could use it to feed some hardware gauge with data, feed it into a data analytics tool or whatever.',
    },
    {
      q: 'Are we monetizing (selling, renting, leasing, etc.) your data in any way?',
      a: 'No.',
    },
    {
      q: 'Are we using your data to train AI models or similar?',
      a: 'No.',
    },
    {
      q: 'Are we using any third-party tracking or analytics technologies?',
      a: 'No.',
    },
    {
      q: 'Where are our servers located?',
      a: 'Germany.',
    },
    {
      q: 'Do we send your data to servers outside of Germany?',
      a: 'No.',
    },
    {
      q: 'Are we making money in any way?',
      a: 'No. Everything is free and open source. We pay for the infrastructure required to run this site with our own money alone. This software is developed in our free time, so we have no income from it.',
    },
    {
      q: 'Can I donate in any way?',
      a: 'No. We do not accept donations. Instead, we suggest you donate to a charity of your choice if you like.',
    },
    {
      q: 'Is it possible to save my dashboards and/or share them with others?',
      a: 'No. This would require us to store your dashboards, which would make privacy and security issues much more difficult.',
    },
    {
      q: 'Is it allowed to use the API of this site directly?',
      a: 'No. Please use the tool through its UI only, as intended. If you want to use the API directly, please contact us via the Github repository page.',
    },
    {
      q: "I don't see any data after starting to fly around in a mission, what might be the issue?",
      a: 'Please check the following: 1) DCS logs, usually at "C:\\Users\\<username>\\Saved Games\\DCS\\Logs\\dcs.log 2) Your browser console, which is usually opened by pressing F12 to show the dev tools.',
    },
    {
      q: 'Do I have to restart DCS after making changes to my dashboard?',
      a: 'No. You do have to restart a mission though. Please note that everytime you change the model, you must build and download the generated files again, and place them in the appropriate locations as instructed by the readme.txt file.',
    },
  ];
}
